services:
  - type: web
    name: planilha-horas-voare
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DATABASE_URL
        value: postgresql://postgres:ACAzZzsq5oVeZAmp@prprnmymsninqxvpifox.supabase.co:6543/postgres?sslmode=require&options=project%3Dprprnmymsninqxvpifox
      - key: EDIT_PASSWORD
        value: Emerson
      - key: EDIT_PASSWORD_2
        value: Bispo
